-- ROWNUM : 순번을 정해놓은 SUUDO COLUMN이다.
-- ㅈ회되는 행의 수를 제한할때 사용
SELECT  ROWNUM, bno, title, writer, content
FROM board
WHERE ROWNUM > 0 AND ROWNUM <= 10
ORDER BY bno;


SELECT * FROM
(SELECT  ROWNUM RN, bno, title, writer, content
FROM board)
WHERE RN > 0 AND RN <= 20;

CREATE TABLE EX_SCORE(
    NAME    VARCHAR2(10),
    score   NUMBER
);



INSERT INTO EX_SCORE VALUES ('김하나', 94);
INSERT INTO EX_SCORE VALUES ('이하나', 100);
INSERT INTO EX_SCORE VALUES ('박하나', 97);
INSERT INTO EX_SCORE VALUES ('정하나', 77);
INSERT INTO EX_SCORE VALUES ('조하나', 87);
INSERT INTO EX_SCORE VALUES ('안하나', 91);
INSERT INTO EX_SCORE VALUES ('유하나', 66);
INSERT INTO EX_SCORE VALUES ('오하나', 85);
INSERT INTO EX_SCORE VALUES ('한하나', 80);
INSERT INTO EX_SCORE VALUES ('성하나', 95);

SELECT * FROM EX_SCORE;

-- 점수가 높은 순으로 5명 검색
SELECT ROWNUM, NAME, SCORE
FROM EX_SCORE
WHERE ROWNUM <= 5
ORDER BY SCORE DESC;

SELECT ROWNUM, NAME, SCORE FROM
(SELECT ROWNUM, NAME, SCORE
FROM EX_SCORE
ORDER BY SCORE DESC)
WHERE ROWNUM <= 5





